# Generated by Django 5.2.9 on 2025-12-13 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
        ('parties', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='partymovie',
            unique_together={('party', 'movie')},
        ),
    ]
