# Generated by Django 5.2.9 on 2025-12-10 14:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('movies', '0002_initial'),
        ('parties', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='party',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parties_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='party',
            name='members',
            field=models.ManyToManyField(related_name='parties', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='partymovie',
            name='added_by_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='party_movies', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='partymovie',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='party_movies', to='movies.movie'),
        ),
        migrations.AddField(
            model_name='partymovie',
            name='party',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='party_movies', to='parties.party'),
        ),
        migrations.AddField(
            model_name='vote',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='movies.movie'),
        ),
        migrations.AddField(
            model_name='vote',
            name='party',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='parties.party'),
        ),
        migrations.AddField(
            model_name='vote',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='vote',
            unique_together={('user', 'party')},
        ),
    ]
