# Generated by Django 5.2.9 on 2025-12-10 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parties', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='party',
            name='join_code',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
