# Generated by Django 5.2.9 on 2025-12-14 20:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
        ('parties', '0002_alter_partymovie_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='party',
            name='winning_movie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='won_parties', to='movies.movie'),
        ),
    ]
